AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Visitor Lambda

Resources:
  LambdaVisitor:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
    Properties:
      FunctionName: CloudResumeVisitorHandler
      Handler: app.handler
      Runtime: python3.11
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          VISITOR_TABLE: CloudResumeVisitors-Dev
      Events:
        VisitorApi:
          Type: Api
          Properties:
            Path: /visitor
            Method: GET
            RestApiId: !Ref VisitorApi

  VisitorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://www.isaac-douglas.com'"